config:
  fromEmail: developer@synesee.com
  emailKeyPrefix: ''
  subjectPrefix: 'Forwarded: '
  forwardMapping:
    info@example.com:
      - example.john@example.com
      - example.jen@example.com
    abuse@example.com:
      - example.jim@example.com
    "@example.com":
      - example.john@example.com
    info:
      - info@example.com

steps:
    - exports.parseEvent
    - exports.buildForwardMap
    - exports.transformRecipients
    - exports.fetchMessage
    - exports.processMessage
    - exports.sendMessage
